#!/bin/bash

# Initialize variables
resolution="1024x780x24"
xterm_cmd="/bin/bash"
additional_cmd="ls"
x11vnc_args=""

while getopts "h?r:a:x:f" opt; do
    printf " -%s '%s'\n" $OPTION $OPTARG
    case "$opt" in
    h|\?)
        help
        exit 0
        ;;
    r)  resolution=$OPTARG
        ;;
    a)  additional_cmd=$OPTARG
        ;;
    x)  xterm_cmd=$OPTARG
        ;;
    f)  x11vnc_args+="-forever "
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

help() {
  echo "./dockapp-start [arg...]"
}

echo "resolution='$resolution'"
echo "cmd='$cmd'"
echo "x11vnc_args='$x11vnc_args'"
echo "leftovers: $@"

# start framebuffer display server
Xvfb :1 -extension GLX -screen 0 $resolution &

# export DISPLAY or you have to use "DISPLAY=:1 /usr/bin/cmd"
export DISPLAY=:1

/usr/bin/openbox-session &

# Wait a bit until the X server is ready
sleep 1

# Launch an additional command in the background
$additional_cmd &

# Launch an xterm with xterm_cmd
xterm -e "$xterm_cmd; bash" &
#xterm -hold -e "$xterm_cmd" &

# Without using the -forever flag the container will stop
# as soon as vncviewer disconnects
#x11vnc -usepw -display :1 -forever
x11vnc -usepw -display :1 $x11vnc_args


# To make sure we can restart this container properly
# Fatal server error: Server is already active for display 1
# If this server is no longer running, remove /tmp/.X1-lock
rm /tmp/.X1-lock

