#!/bin/bash

# Initialize variables
name="dockapp"
image="jann/ubuntu:14.04v2"
vnc_passwd_file="$HOME/.docker/vnc/passwd"
share="$HOME/share/docker"
network=1
socket="$HOME/share/docker/x11vnc-socket"
hostname="docker"

start_args=""
docker_args=""

run() {
  echo "dockapp: creating the container and starting it"
  shift $((OPTIND - 1))
  while getopts "r:a:x:fu" OPTION "$@"; do
    printf " -%s '%s'\n" $OPTION $OPTARG
    case "$OPTION" in
    r)  start_args+="-$OPTION $OPTARG "
        ;;
    a)  start_args+="-$OPTION $OPTARG "
        ;;
    f)  start_args+="-f "
        ;;
    u)  start_args+="-u "
        docker_args+="--net=none "
        ;;
    esac

  done
  shift $((OPTIND - 1))
  #printf "Leftover args: '%s'" "$@"

  # delete old sockets
  if [ -S "$socket" ]; then
    rm "$socket"
  fi

  docker run -d --name $name -h $hostname -v $share:/share:rw $docker_args $image /dockapp-start $start_args
}

view() {
  echo "dockapp: running vncviewer"
  if [ -S "$socket" ] #see man test
  then
        ssvnc-viewer "$socket"
  else
        vncviewer -PasswordFile=$vnc_passwd_file $(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $name):5900
  fi

}

start() {
  echo "dockapp: starting a stopped container"
  docker start $name
}

stop() {
  echo "dockapp: stoping a container"
  docker stop $name
}

pause() {
  echo "dockapp: pause a container"
  #docker pause $name
}

unpause() {
  echo "dockapp: unpause a paused container"
  #docker unpause $name
}

ps() {
  echo "dockapp: active dockapp containers:"
  docker ps -a |grep $name
}

default() {
  if ! docker inspect $name &> /dev/null; then
    echo "dockapp: container $name not running, starting it"
    dockapp run -u -r 1280x1000x24
  else
    start
  fi

  sleep 3
  view
}

help() {

echo "
SYNOPSIS
   dockapp [COMMAND] [arg...]
COMMANDS
    run
        -r,
        -a,

    view
    start
    stop
    pause
    unpause
    help
"

echo "dockapp [run|view|start|stop|pause|unpause|help] [arg...]"
echo "dockapp run -r 1280x1024x24 -a firefox -x top"
echo "dockapp run -u -r 1280x1000x24"
echo "dockapp"

}


if [ -z "$1" ]
then
  echo "No arguments given, using defaults."
  default
elif [[ $1 =~ ^(run|view|start|stop|pause|unpause|ps|help)$ ]]; then
  "$@"
else
  echo "Invalid argument $1" >&2
  help
  exit 1
fi


